version: "3.4"

networks:
  netcoreapp:

services:

  msdatabase:
    container_name: msdatabase
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    ports:
      - "14349:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "r00t.ROOT"
      MSSQL_PID: Express
    networks:
      - netcoreapp

  aspapi:
    container_name: aspapi
    build:
      context: .
      dockerfile: ./blog-rest-api-asp/web-blog/Dockerfile
    ports:
      - "5000:7185"
    depends_on:
      - msdatabase
    environment:
      DB_HOST: "msdatabase"
      DB_PORT: "1433"
      DB_NAME: "web-blog-asp-api"
      DB_SA_PASSWORD: "r00t.ROOT"
    networks:
      - netcoreapp
    restart: on-failure
    volumes:
      - type: bind
        source: E:/Upload
        target: /app/uploads

  vue-front-end:
    container_name: vue-front-end
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./blog-app-vuejs/Dockerfile
    ports:
      - "8081:80"
    depends_on:
      - aspapi
    networks:
      - netcoreapp
      
  vue-front-end-admin:
    container_name: vue-front-end-admin
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./blog-app-admin-vuejs/Dockerfile
    ports:
      - "8086:85"
    depends_on:
      - aspapi
    networks:
      - netcoreapp          